#cloud-config
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
  - sudo firewall-cmd --permanent --add-port=6443/tcp
  - sudo firewall-cmd --permanent --add-port=22/tcp
  - sudo firewall-cmd --reload